name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Upload file '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Face Detection
        - Object Detection
        - API
        - Web Interface
        - Docker/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Mode
      description: How are you running the application?
      options:
        - Local (python run.py)
        - Docker (simple mode)
        - Docker Compose (scalable mode)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: e.g., v1.2.3 or commit hash
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Please provide relevant environment details:
        - OS (Linux, macOS, Windows)
        - Python version
        - Docker version (if applicable)
        - Browser (if web interface issue)
      placeholder: |
        OS: Ubuntu 22.04
        Python: 3.11.5
        Docker: 24.0.5
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant log output
      render: shell
      placeholder: Paste logs here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or files about the problem
      placeholder: Any other relevant information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
