apiVersion: v1
kind: Service
metadata:
  name: {{ include "recognize.fullname" . }}-web
  labels:
    {{- include "recognize.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "recognize.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
