---
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.JBOT_APP_ID }}
          private-key: ${{ secrets.JBOT_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Release type determines versioning and changelog format
          release-type: simple
          token: ${{ steps.app-token.token }}

      # Optional: Build and push Docker image on release
      - name: Build and Push Docker Image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Major version: ${{ steps.release.outputs.major }}"
          echo "Minor version: ${{ steps.release.outputs.minor }}"
          echo "Patch version: ${{ steps.release.outputs.patch }}"
          # Add your Docker build and push commands here
          # docker build -t recognize:${{ steps.release.outputs.tag_name }} .
          # docker push recognize:${{ steps.release.outputs.tag_name }}
